# Generated by Django 4.2.4 on 2023-08-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_HealthTrainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='hour',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='goal',
            name='minute',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
