# Generated by Django 4.2.4 on 2023-08-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_HealthTrainer', '0004_alter_workout_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='goal',
            new_name='user',
        ),
    ]
